### ISSUE TITLE
Facets and their aggregations must be configurable on any field

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-yase#26]
Now that tags are no longer a special hardcoded field, facets and aggregations must be configurable, and the code using the configuration to get counts etc must be reworked.

**Comment by ComLock** [comment]
Simplest GUI is [Multiple select fields]
Which will present facets for all found values. That will not present empty tags though.
Also one might want to control the order of fields and/or facets.

So a little more complex:

An list you can add, remove and reorder which contains a
[Single select field dropdown]
When a field is selected the admin is presented with

An list you can add, remove and reorder Tags which are presented as a
[Single select tag dropdown]

This all works fine as long as it should not be possible to aggregate on multiple fields within a facet category. The aggregation bucketname will be the fieldName.

For now we will let the order of the tags in the config determine the order of the facets in the result. Another option could be to enable config for the terms aggregation order setting. For example "_term ASC" and "_count DESC"

**Comment by sigdestad** [comment]
Has the implementation of tags changed?

**Comment by ComLock** [comment]
The facet builder uses req.params.facets which currently uses the node._path.
The problem is node._path doesn't match aggregation values.

Example:
node._path: /tags/fieldName/underscored-sanitized-tag-name
aggregation value: underscore tag name with spaces

Having a lot of code which translates back and forth between them is ugly and bad!

Since aggregations works on fields, I think the req.params should reflect that:
?q=searchString&source=collection&information-type=sometype&lang=norsk

There could be problem if a field name conflicts with a param name that is already in use.
So req.params received from the clientSide should be mapped somehow.

**Comment by ComLock** [comment]
Which would make for nicer urls too.
