### ISSUE TITLE
IDEA: Hightlight using "reverse" ascii folding

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-yase#30]
I'm thinking that I can use ascii folder on the incoming string.
Then find the indexes of matches in the ascii folded string.
And then use those indexes to highlight the original string.

This only works if the ascii folding keeps the number of characters constant.

**Comment by ComLock** [comment]
https://www.elastic.co/guide/en/elasticsearch/guide/current/asciifolding-token-filter.html

**Comment by ComLock** [comment]
Search for "œsophagus" does match "oeophagus", but does not get highlighted.

https://no.wikipedia.org/wiki/Akutt_aksent

**Comment by ComLock** [comment]
coöperation

**Comment by ComLock** [comment]
"café au lait" has hits both ways so you can use that for testing

**Comment by ComLock** [comment]
Or how about this.
Split the search query into words and ascii fold them.
Split the incoming text into words and loop over them, in the loop ascii fold each word before comparing with the ascii folded query words.

In order for length limiting to work, you may need two passes.
First pass simply figures out the index of the first match and figures out how many chars before and after that needs to be kept. While the second pass applies the highlighting.

Perhaps one shouldn't strictly enforce the length limit on chars, but try to get as close as possible without splitting a word on the beginning or the end.

**Comment by ComLock** [comment]
This is actually more complex due to word separators etc. So one would need a tokenzier, etc.
This is really a reimplementation of something that elastic already does, so I think waiting for Enonic XP 7.0 is the way to go on this one.

**Comment by sigdestad** [comment]
Good decision. NB! The feature is due for 7.1
