### ISSUE TITLE
Connection mezz

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-yase#47]
When running the same searchPage under /portal/master and vhost I noticed differences.
This happens because the connections are made with different principals.
There needs to be control over the connections.

Currently connections are made in numerous javascript files, which becomes totally confusing.

* To see and use every part of the YASE admin, adding the role Yase administrator should be enough.

Making a search page is done by calling a javascript library function.

* Anyone with the cms.admin role should be able to use the interface selector service.

Currently collection data doesn't have granulated access control.
As such it should be possible to run the search function as system.everyone.

The search function needs to fetch various stuff (like synonyms) from the config repo.

* Using the "com.enonic.yase.read" role should work both for that.

And when doing multiRepoConnect, and connect to the collection repos.

**Comment by sigdestad** [comment]
Hmm.. how is /portal/master related to the yase interface? All back-end url's must be within /admin/tool/<yase-something>?

**Comment by ComLock** [comment]
@sigdestad /portal/master is only related to the frontend apps.

**Comment by ComLock** [comment]
All the admin ui is tested and works. There is no longer any difference in search results between /portal/master and vhost.

What remains to be testet is crawling.
